version: "3.8"

services:
  key-sys-api-ts:
    image: bananaztech/key-sys-api-ts:latest
    container_name: key-api-ts-prod
    restart: always
    ports:
      - "3300:3000"

networks:
  default:
    external:
      name: frontend