version: "3.8"

services:
  key-sys-api-ts:
    image: bananaztech/key-sys-api-ts:latest
    container_name: key-api-ts-prod
    restart: always
    environment:
      DB_PORT: 3306
      DB_HOST: "example.com"
      DB_USER: "Key-API"
      DB_PWD: "example"
      DB_NAME: "keys"
    ports:
      - "3300:3000"

networks:
  default:
    external:
      name: frontend
